# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore
    - name: Run tests
      env:
        dbConnectionString: ${{ secrets.DBCONNECTIONSTRING }}
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build_and_test # Só executa se os testes passarem
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Fly.io CLI
      run: |
        curl -L https://fly.io/install.sh | sh
        echo "$HOME/.fly/bin" >> $GITHUB_PATH

    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.Deploy_Token }}
      run: |
        cd TesteSygnal
        flyctl deploy --remote-only
